name: Replicate Issue to Fork

on:
  issues:
    types: [opened]

jobs:
  replicate_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create issue in fork repo
        env:
          FORK_OWNER: "ash-hun"
          FORK_REPO: "infra_test"
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          # 포크 레포에 issue 생성 권한이 있는 PAT (repo 권한 필수)
          TOKEN: ${{ secrets.FORK_GITHUB_TOKEN_JH }}
        run: |
          # 이슈를 생성할 API 엔드포인트
          FORK_ISSUE_URL="https://api.github.com/repos/${FORK_OWNER}/${FORK_REPO}/issues"
          
          # cURL로 POST 요청 (JSON payload)
          curl -s -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${FORK_ISSUE_URL}" \
            -d @- <<EOF
          {
            "title": "${ISSUE_TITLE}",
            "body": "${ISSUE_BODY}"
          }
          EOF
